// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:dependencies_module/dependencies_module.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1kXoEFw_wK1yfVzSEAwi_f3g5lNuhxCg',
    appId: '1:412689419937:web:271288e511a6d7cbdc2ae0',
    messagingSenderId: '412689419937',
    projectId: 'registro-protocolo-mob-ser',
    authDomain: 'registro-protocolo-mob-ser.firebaseapp.com',
    storageBucket: 'registro-protocolo-mob-ser.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmA4k-W2lxet2eJToDkV4Cf9IsDldXtrA',
    appId: '1:412689419937:android:252454cab866a57ddc2ae0',
    messagingSenderId: '412689419937',
    projectId: 'registro-protocolo-mob-ser',
    storageBucket: 'registro-protocolo-mob-ser.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvF9YMxlZpemLTpQ6tH1CujbdW073XApI',
    appId: '1:412689419937:ios:4b4030c2a5c1904fdc2ae0',
    messagingSenderId: '412689419937',
    projectId: 'registro-protocolo-mob-ser',
    storageBucket: 'registro-protocolo-mob-ser.appspot.com',
    iosClientId:
        '412689419937-c18l87j9hub3ij1c2e8m67umtqup1ecr.apps.googleusercontent.com',
    iosBundleId:
        'br.com.registroprotocolomobser.appClienteRegistroProtocoloMobSer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvF9YMxlZpemLTpQ6tH1CujbdW073XApI',
    appId: '1:412689419937:ios:4b4030c2a5c1904fdc2ae0',
    messagingSenderId: '412689419937',
    projectId: 'registro-protocolo-mob-ser',
    storageBucket: 'registro-protocolo-mob-ser.appspot.com',
    iosClientId:
        '412689419937-c18l87j9hub3ij1c2e8m67umtqup1ecr.apps.googleusercontent.com',
    iosBundleId:
        'br.com.registroprotocolomobser.appClienteRegistroProtocoloMobSer',
  );
}
